version: '3'

vars:
  CLIENT_APP: greeter_client
  SERVER_APP: greeter_server
  REGISTRY: ""
  REPOSITORY: buzzsurfr
  TAG: latest

includes:
  client:
    taskfile: ./greeter_client
    dir: ./greeter_client
  server:
    taskfile: ./greeter_server
    dir: ./greeter_server

tasks:
  proto:
    desc: "[Re]Generate go code for protocol buffers."
    cmds:
      - protoc -I {{.PROTODIR}} --go_out=paths=source_relative:{{.PROTODIR}} --go-grpc_out=paths=source_relative:{{.PROTODIR}} helloworld.proto
      # - protoc -I /go/src/github.com/buzzsurfr/grpc-examples/examples/helloworld/helloworld --go_out=/go/src/ --go-grpc_out=/go/src/ helloworld.proto
